name: MyPlugin
version: ${version}
description: Doing various things on the server.
author: Wojciech Paruch <teamaster69@proton.me>

main: me.teamaster.myplugin.MyPlugin
commands:
    blocklog:
        aliases: [blocklogger, inspect]
        description: Inspect the block logs.
    players:
        aliases: [list, kto]
        description: Check who's currently online.
    myplugin-reload:
        aliases: reload-myplugin
        description: Reload the configuration of MyPlugin.
    info:
        aliases: rules
        description: Get some information about the server.
